### ISSUE TITLE
As an operator, I want to remove cg-dashboard (5/18)

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/product#1319]
A bug in stratos is currently requiring us to continue to run cg-dashboard: https://github.com/cloudfoundry/stratos/issues/4103

Once this issue is fixed, deployed and validated in cg, we should remove cg-dashboard.

## Acceptance Criteria
* [x] GIVEN The stratos bug is fixed
  AND stratos is updated in production with the bug fix
  WHEN a user accesses dashboard-deprecated.fr.cloud.gov
  AND looks in the docs for user management information
  THEN they are redirected to stratos
  AND the docs match stratos

--- 

## Security considerations

be sure the stratos fix meets our needs. For example, a user should not be able to see and search for all users in a system. Instead, they should have to enter an exact username when setting a role.

## Implementation sketch

* [x] Remove CircleCI access to the cg-dashboard repo (remove the webhook)
* [x] Archive the cg-dashboard repo
* [x] Update docs and remove references to dashboard-deprecated
* [x] Add a redirect for the legacy dashboard to the current Stratos dashboard
* [x] Validate Stratos dashboard docs on docs.cloud.gov show the correct procedure to manage users

**Comment by bengerman13** [comment]
I think the AC here is overly-prescriptive of how to fix this.
It's possible Stratos will never fix the bug we reported, or that it will not be done in a timely manner, so we may need to instead work around it by plumbing the functionality into cg-uaa-extras or something like that

**Comment by karareinsel** [comment]
Will be blocked until the next stable release of Stratos. Ping Stratos to nudge them to cut a release.

**Comment by tammersaleh** [comment]
For reference, we need this merged PR https://github.com/cloudfoundry/stratos/pull/4172, which we hope will be in the next stable Stratos release.

**Comment by tammersaleh** [comment]
[Pinged the stratos team in Slack](https://cloudfoundry.slack.com/archives/C80EP4Y57/p1586193130024100).

**Comment by karareinsel** [comment]
@tammersaleh can we ping the Stratos team again?

**Comment by tammersaleh** [comment]
Here's [the slack thread](https://cloudfoundry.slack.com/archives/C80EP4Y57/p1586193130024100), and it looks like [they just released the 3.1 RC](https://github.com/cloudfoundry/stratos/releases/tag/3.1.0-rc.1), so hopefully the final release is just around the corner.  If we don't see a final in a week, I think we should ping them.

**Comment by mheadd** [comment]
Given that we've had a few customer inquiries relating to this issue, wondering if we need to do any follow up or outreach when the change is made.

**Comment by karareinsel** [comment]
That's a good point @mheadd. We could put up a blog post or announce in office hours.

**Comment by ccostino** [comment]
I've started taking a look at this and testing the flow in the new 3.1.0 Stratos dashboard we have deployed and sure enough, the PR on the Stratos side is merged and working.  It also accounts for the security consideration we have noted: you cannot see all users in the system, you must drill down to a specific `org` or `space`, and to add a user you must know their username and enter it in exactly to set a role(s) for that user in a given `org`/`space`.

You cannot add new users directly in the dashboard either, a user must exist in the system in order to add them to another `org`/`space`.  To test this, I performed the following steps:

- I registered a new user by signing up for a sandbox account
- I logged into my admin account, and add that user as a `Manager` in an organization.
- I then logged in as that new user to the new dashboard
- As the new user, I found another existing sandbox user I had in the system and added them as a 'User' to an organization

An interesting thing happened with this, though:  I could not see the newly created user in the organization, just the second user I had added.

I suspect this might be because I added the first new user to the organization before logging in with them, which means the account wasn't fully setup/verified; this could be an issue and something to specifically call out in guide, if not also fix if need be.

I took screenshots of what I had done and will test again with a fully set account to see if that user then shows up in the list in addition to the secondary added user.

Thank you @bengerman13 for the help and answering my questions!

**Comment by ccostino** [comment]
It appears that the issue may have been that I didn't add my first new user as a `User` in addition `Manager`.  Once I did that they showed up in the list.

**Comment by ccostino** [comment]
Once the instructions are vetted and verified in https://github.com/cloud-gov/cg-site/pull/1656, we ought to be able to send an updated notice about this to our customers that the new dashboard is ready to use and the old one will be retired.

**Comment by ccostino** [comment]
I have created a [draft StatusPage notice](https://docs.google.com/document/d/10QNNp4b1zyHeOXVLMkR0Pm2u2j5KIfKDPk1NUWvIBJ0/edit#heading=h.rshmvevwgtf9).  Please edit and provide feedback!

**Comment by ccostino** [comment]
StatusPage notice sent!  Deprecation is set for **05/18/2020**.

**Comment by ccostino** [comment]
This is now complete!  Thank you @ChrisMcGowan and @bengerman13 for the help, I appreciate it!
