### ISSUE TITLE
Enable db.t2/t3.micro instances for sandbox accounts

### ISSUE THREAD

**Issue by RonWilliams** [cloud-gov/product#1400]
To allow deprecation of the shared database environment, a replacement service must exist for sandbox accounts. Enable use of the db.t2/t3.micro instance types for sandbox users.

**Comment by ccostino** [comment]
As a part of this, I'd like to see if we can adjust the output of `cf marketplace` so that it doesn't list plans a user doesn't have access to.  The broker accounts for this and will fail with a message, but it's confusing to see all plans listed when you don't have access to them.

If it's not too much effort, I'll tweak this.

Also, @RonWilliams, does it make sense to list the `micro` and `small` instances as `free` in our service plan catalog?  That's the easiest way to account for this change, but I want to make sure that's in line with our business intent and policies for the future.

**Comment by ccostino** [comment]
We should also update the [RDS documentation on our site](https://cloud.gov/docs/services/relational-database/) to include a specific note about which instances are available for sandbox users, much like the [identity provider](https://cloud.gov/docs/services/cloud-gov-identity-provider/) and [service account](https://cloud.gov/docs/services/cloud-gov-service-account/) services documentation does.

**Comment by ccostino** [comment]
@RonWilliams and I caught up about this and we're going to go with the path of modifying the service plans in the catalog to reflect what should be available.  I have opened two PRs, one to update the catalog itself and one to add this information to our RDS documentation.

**Comment by ccostino** [comment]
These PRs have been updated with some minor adjustments, including a couple of fixes contributed by @patphongs (thank you!).  They should be ready for full review at this point!

**Comment by ccostino** [comment]
This work is now complete and sandbox accounts are able to create `micro-psql` and `small-mysql` RDS instances!  The [RDS documentation on our site](https://cloud.gov/docs/services/relational-database/) is also updated to reflect this.
