### ISSUE TITLE
Unwinding kubernetes

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/product#1535]
In order to spin down kubernetes, the team needs to review it's integrations into the rest of the platform and plan changes to remove k8s from the environment.

## Acceptance Criteria
* [x] Discrete tasks documented and new issues created
--- 

## Security considerations
Could vary once work is laid out and smaller tickets created 

## Implementation sketch
* [x] Have a engineering meeting to break down the problem into smaller stories
* [x] Create smaller tickets of work in prep for decom

**Comment by bengerman13** [comment]
Some tasks to be done:
- remove log group checks from awslogs.sh in prometheus deployment
- remove k8s broker checks from prometheus alert rules
- remove kube_state_metrics_exporter from prometheus manifest (this probably needs to be done _before_ shutting down k8s, because prometheus fails to start when it can't reach this, I think)

**Comment by ccostino** [comment]
Meeting is scheduled for 3/2 at 2 PM ET.

**Comment by ccostino** [comment]
[A notes doc](https://docs.google.com/document/d/1_RW4ja2wtxJiA1M9tcB4rY50N9BhZ6l7Kn9MvwEZ0FU/edit) was created during the meeting and new issues are being created for future triage.  Thank you, @bengerman13 and @ChrisMcGowan!
