### ISSUE TITLE
Port (Federalist) Zendesk content to new instance by August 31st

### ISSUE THREAD

**Issue by mogul** [cloud-gov/product#2074]
In order to retain our support activity history, we want historical Pages activity migrated from federalist.zendesk.com to cloud-gov.zendesk.com.

## Acceptance Criteria
* [ ] GIVEN I am logged into cloud-gov.zendesk.com as an Agent \
  WHEN I look at issues \
  THEN I see all expected Pages support activity from before June 2022 is present.

--- 

## Security considerations
Only content will be migrating. Settings for the new instance were part of a previous migration.

## Implementation sketch

* [ ] Can we pay Zendesk to do this for us?
* [ ] If not, can we pay a contractor to do this for us?
* [ ] If not, can we use a community-provided tool?
* [ ] If not, can we write our own migration using the Zendesk API?
* [ ] Delete the federalist.zendesk.com account.

**Comment by ArsHaider** [comment]
As of 7/28/2022: Brain Cell (Zendesk migration people) are getting started on the migration. Additionally, Zendesk has extended access to our old account for 30 days to ensure we can get the migration done.

**Comment by ArsHaider** [comment]
As of 7/28/2022: Brain Cell (Zendesk migration people) are getting started on the migration. Additionally, Zendesk has extended access to our old account for 30 days to ensure we can get the migration done.

**Comment by ArsHaider** [comment]
As of 8/2/2022: Had a meeting with the team from BrainSell, are requesting access to admin login information for both instances of old cloud gov Zendesk instance and federalist Zendesk instance. Scheduled to have next meeting to start the migration process at 11 am Thursday 8/4/2022.

**Comment by Ephraim-G** [comment]
*Test Migration - 11 am Thursday 8/4/2022

* Requesting admin access to Cloud-gov-new as well (3) instances in total

**Comment by Ephraim-G** [comment]
Notes from test migration 1 debrief meeting with Brainsell on 8/11

- Only customers with tickets associated to their email address could be migrated. For the actual migration this will not be the case. All customers regardless of ticket association will be brought over. 
- Cannot save/transfer reference # of tickets due to it being an URL. Will tag tickets with either Pages/Cloud.gov tags to differentiate. Brainsell will work with Zendesk support to identify any work around.
- Triggers, alerts and automations will be either ported over or recreated in the new instance.

**Comment by Ephraim-G** [comment]
Updated deadline July 30th -> August 31st
