### ISSUE TITLE
Investigate using S3 glacier to store "inactive" customer & platform logs after 12 months

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2152]
In order to comply with EO M-21-31, we want customer log data retained for 12 months in active state and 18 months in in-active state.

After 12 months when data is "inactive", we want to consider using S3 Glacier for storage instead of the regular tier of storage because it costs less money.

## Background

- [Presidential Memorandum M-21-31](https://www.whitehouse.gov/wp-content/uploads/2021/08/M-21-31-Improving-the-Federal-Governments-Investigative-and-Remediation-Capabilities-Related-to-Cybersecurity-Incidents.pdf).
- [Notes from discussion with assurance team about M-21-31](https://docs.google.com/document/d/11PcgXjs42hrYu8o91ep2vmdS5TkjmTw69Br0P1BvsBg/edit)

## Acceptance Criteria

* [ ] Assessment is documented on the value of using S3 glacier to store "inactive" logs
  - [ ] If using S3 Glacier is deemed worthwhile, ADR is drafted
  - [ ] If using S3 Glacier is deemed not worthwhile, ticket is complete

--- 

## Security considerations

Changes to retention period will allow us to comply with EO M-21-31

## Implementation sketch

* [ ] Research/document potential S3 cost savings of using S3 Glacier vs engineering time cost time to implement
* [ ] If using S3 Glacier is deemed worthwhile:
  - ADR is drafted
  - New ticket to implement S3 glacier for inactive logs is written

**Comment by dandersonsw** [comment]
Production platform logs currently transitions from active storage to One Zone-IA storage, and then gets deleted after a set amount of time.

**Comment by dandersonsw** [comment]
Based on current s3 usage for logs we aren't spending very much. However, using One Zone-IA storage for some of the logs would cut the storage costs for those logs by a little more than half, and since we are increasing the amount of logs we store this isn't insignificant.

**Comment by dandersonsw** [comment]
Implementation for platform logs would be simple. The days field would just need to be updated for the [current policy](https://github.com/cloud-gov/cg-provision/blob/5622891177a40021289e922169e234271fc3ae9f/terraform/modules/logsearch/platform_log_bucket.tf#L17).

For tentant logs, since we probably don't want to implement this for other buckets, we would need to create a [new rule](https://github.com/cloud-gov/cg-provision/blob/5622891177a40021289e922169e234271fc3ae9f/terraform/modules/s3_bucket/encrypted_bucket/encrypted_bucket.tf#L30) that could be applied to only the logs bucket, with the **transition** section enabled and defined.

**Comment by dandersonsw** [comment]
We have now implemented a transition policy in s3 that moves logs to onezone_ia storage after 365 days: https://github.com/cloud-gov/cg-provision/pull/1125
