### ISSUE TITLE
Research migration plan for site webhooks

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/product#2194]
In order for customers to migrate to pages, their sites' webhooks will need to be update them to point to pages and not federalist.

## Background
- https://github.com/18F/federalist/blob/9dcc6645072cada2ccc5198fade800a81b033c2d/api/services/GitHub.js#L169-L190

## Acceptance
- TDB

**Comment by drewbo** [comment]
As detailed [here](https://docs.google.com/document/d/1ct3nykSLqPChHftlKWVZJQ4DoXQFPYAX3y6U62ubIS8/edit#heading=h.o41q1pc9fsqa):
- During part of the migration period, the Federalist API will remain up to accept webhook POST requests even when the UI itself is shut down.
- We will ask users to manually update their webhook targets to pages during the migration process

**Comment by drewbo** [comment]
We'll track webhook requests per application with a [saved logstash query](https://logs.fr.cloud.gov/app/discover#/view/a1d6b0b0-23c3-11ed-9eb4-2d60d06d08d6). The exported csv can be parsed with this "one-liner" to show the latest author and repo:
```sh
cat export.csv | csvcut -c "@message" | tail -n +2 | awk 'length<16384' | sed -E 's/^\"//g' | sed -E 's/\"$//g'  | sed -E 's/\"\"/"/g' | sed -E 's/info: HTTP POST \/webhook\/github //g' | jq -r '.meta.req.body | [ .repository.html_url, .sender.login ] | @csv'
```

**Comment by drewbo** [comment]
Adding one other research note before closing: our current plan is to stop the flow of new Federalist webhook requests by not allowing new sites to be created on Federalist. As a backup option, we can also change the [webhook URL environment variable](https://github.com/cloud-gov/pages-core/blob/main/config/webhook.js) to the Pages endpoint which will create updated webhooks even if the site is created on Federalist rather than Pages.
