### ISSUE TITLE
Create a customer survey

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2235]
We would like to create a cloud.gov customer survey that we distribute on a regular basis (quarterly?) to assess customer satisfaction and get a clear picture of their needs.

Possible survey questions:

- How satisfied are you with the cloud.gov platform? (scale of 1-10 with a box to explain answer)
- How satisfied are you with cloud.gov support? (scale of 1-10 with a box to explain answer)
- What feature or service would you most like to see added to cloud.gov?
- Is there anything else you'd like to tell us about your experience with cloud.gov?

Tactical questions:

- What service can we use for the survey? Google Forms seems ideal and simplest if it's allowed
- What laws/regulations are there around customer surveys that we need to observe?

**Comment by jameshochadel** [comment]
@kelleyconfer set this up and is going to send it out in this month's newsletter! We're hoping to get some feedback before the PI planning. We used the questions from this work item, but used a 1–5 scale for the first two.

Tactical answers: 

* We're using Touchpoints for the survey
* Since we're surveying government employees, the survey is voluntary, and we're using free software, we don't believe there are any applicable rules we need to follow.

**Comment by markdboyd** [comment]
@jameshochadel @kelleyconfer Awesome! Great work. Can we close this ticket then?

**Comment by jameshochadel** [comment]
Yep, I was planning to close it once the newsletter goes out.

**Comment by markdboyd** [comment]
This is complete
