### ISSUE TITLE
Build `ubuntu-hardened` base image

### ISSUE THREAD

**Issue by jameshochadel** [cloud-gov/product#2566]
In order to base all docker containers on a hardened operating system, let's create a single hardened base image based on Ubuntu. 

Create a new repository named something like `ubuntu-hardened`. Create a Dockerfile that is based on the `ubuntu:22.04` image (or a more specific version?) and runs the hardening script. See [cg-deploy-concourse-docker-image](https://github.com/cloud-gov/cg-deploy-concourse-docker-image/blob/main/task/harden-concourse-tasks/Dockerfile) as a starting point. 

Also depends on #2567 for actually building the image in Concourse.

**Comment by pburkholder** [comment]
This is hung up on an interesting licensing question:

---

Cloud.gov runs software on Ubuntu, a free, open-source operating system. Ubuntu is the base operating system for many of our Docker container images, which package executable code. Due to new compliance requirements, [cloud.gov](http://cloud.gov/) must only run "hardened" container images in our authorization boundary. We have purchased an Ubuntu Pro subscription from Canonical, the company that owns Ubuntu, which provides us access to a script called "usg" that hardens Ubuntu to the required baseline. If you run usg on an Ubuntu container, the container is considered hardened. It's my understanding that by purchasing Ubuntu Pro we are licensed to use usg to harden Ubuntu images for our own use in the platform.

We want to create a new source code repository that automates the process of hardening the free, publicly-available Ubuntu image using the paid (proprietary?) usg script. The repository itself will not include Ubuntu or the hardening program code, but will include code that:

    Downloads the FOSS Ubuntu image and the usg program. Ubuntu is publicly available and free. Usg is publicly available for download but does not work without a license key.
    Runs usg with our license key (which will not be publicly visible)
    Produces a hardened Ubuntu image
    Pushes the image to a private registry which is only accessible to the [cloud.gov](http://cloud.gov/) platform. 

My question is this. We conventionally license our repositories as CC0, placing them in the public domain. Can we use that license on this repository?

I believe the answer is yes, because:

    We are not re-publishing any of Canonical's code, and therefore we would not be re-licensing it. All of the code in the repository would be written by our team; it would just run usg on Ubuntu when it runs.
    We are not publishing the executable code that results from running the paid script publicly (e.g. a hardened Ubuntu image), so we are not violating the terms of our license or re-licensing the Ubuntu executable.

I presume, though, that a definite answer depends on the licenses of Ubuntu and usg / Ubuntu Pro. I also want to see if we must include their licenses in the repository. (Attribution? I don't know the terminology). 

Here is the Ubuntu Pro website: https://ubuntu.com/pro I have not located a license or terms of use for Ubuntu Pro on the site.

**Comment by jameshochadel** [comment]
Conversation with TTS legal team documented here: https://groups.google.com/a/gsa.gov/g/cloud-gov-compliance/c/HFB9_1hlWrc

**Comment by dtamasang2** [comment]
Repo for ubuntu hardened docker images created and pipeline tested successfully. https://github.com/cloud-gov/ubuntu-hardened/tree/main
