### ISSUE TITLE
Decide which resource images in spreadsheet are redundant

### ISSUE THREAD

**Issue by jameshochadel** [cloud-gov/product#2569]
Related to #2538. Review through how each pipeline uses the images in the spreadsheet and decide if some are redundant and be consolidated.

**Comment by dandersonsw** [comment]
Updated spreadsheet with a 'plan' column for each image.

3 images for sure can be replaced with our harden-concourse-task
7 images may possibly be replaced by harden-concourse-task if we add/install more to the harden-concourse-task image
2 images may be replaced by a hardened oracle-client image

All of the resource type image needs its own hardened image since they require specific `check`, `in`, and `out` scripts

**Comment by dandersonsw** [comment]
The domain broker images could either reference the harden-concourse-task image, or we can have it reference our base image.
